{
  "swagger": "2.0",
  "info": {
    "title": "Documentation API",
    "version": "1.0.0",
    "description": "API pour un site de gestion de reservations pour 3 chambres d'hôtes chez un particulier."
  },

  "servers": [
    {
      "url": "http://localhost:5000/",
      "description": "Development server"
    }
  ],
  "paths": {
    "/clients/getAll": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Récupère tous les clients de la base.",
        "responses": {
          "200": {
            "description": "OK. Retourne la liste de tous les clients.",
            "examples": {
              "application/json": [
                {
                  "_id": "651d7ea02a10f6207ad47ef8",
                  "id": 1,
                  "nom": "Gambert",
                  "prenom": "Adrien",
                  "adresse": "12 rue les bains",
                  "telephone": "0612345678",
                  "email": "test@gmail.com",
                  "password": "$2b$10$elC6nwU4Mg8TaJLrikrhI.TFR7Mwx0DxZ8wzw3LRS57OF0rJi",
                  "__v": 0
                },
                {
                  "_id": "651d7ea02a10f6207ad47ef8",
                  "id": 34,
                  "nom": "Buathier",
                  "prenom": "Tom",
                  "adresse": "12 rue les betes",
                  "telephone": "0765436254",
                  "email": "test.test@gmail.com",
                  "password": "$2b$10$elC6nwU4Mg8TaJLrikrhI.TFR7Mwx0DxZ8wzw3LRS57OF0rJi",
                  "__v": 0
                }
              ] 
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/clients/get": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Récupère un client en fonction de son token",
        "security": [
          {
            "Bearer": [] 
          }
        ],

        "responses": {
          "200": {
            "description": "Opération réussie. Retourne le client correspondant à l'ID.",
            "examples": {
              "application/json": [
                {
                  "_id": "651d7ea02a10f6207ad47ef8",
                  "id": 45,
                  "nom": "Gambert",
                  "prenom": "Adrien",
                  "adresse": "12 rue les bains",
                  "telephone": "0612345678",
                  "email": "test@gmail.com",
                  "password": "$2b$10$elC6nwU4Mg8TaJLrikrhI.TFR7Mwx0DxZ8wzw3LRS57OF0rJi",
                  "__v": 0
                }
              ] 
            }
          },

          "401": {
            "$ref": "#/components/responses/401"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }

        }
      }
    },
    "/clients/getReservation": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Permet de récupérer une reservation en fonction de l'id du client",
        "security": [
          {
            "Bearer": [] 
          }
        ],
        "responses": {
          "200": {
            "description": "Opération réussie. Retourne la reservation correspondant à l'ID"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/clients/create": {
      "post": {
        "tags": [
          "Clients"
        ],
        "summary": "Crée un nouveau client",
        "parameters": [
          {
            "in": "formData",
            "name": "nom",
            "type": "string",
            "required": true,
            "description": "Votre nom"
          },
          {
            "in": "formData",
            "name": "prenom",
            "type": "string",
            "required": true,
            "description": "Votre prenom"
          },
          {
            "in": "formData",
            "name": "adresse",
            "type": "string",
            "required": true,
            "description": "Votre adresse"
          },
          {
            "in": "formData",
            "name": "telephone",
            "type": "string",
            "required": true,
            "description": "Votre telephone"
          },
          {
            "in": "formData",
            "name": "ville",
            "type": "string",
            "required": true,
            "description": "Votre ville"
          },
          {
            "in": "formData",
            "name": "codePostal",
            "type": "string",
            "required": true,
            "description": "Votre code postal"
          },
          {
            "in": "formData",
            "name": "email",
            "type": "string",
            "required": true,
            "description": "Votre email"
          },
          {
            "in": "formData",
            "name": "password",
            "type": "string",
            "required": true,
            "description": "Votre mot de passe"
          }
        ],
        "responses": {
          "200": {
            "description": "Opération réussie. Retourne le client créé.",
            "examples": {
              "application/json": [
                {
                  "id": 54,
                  "nom": "U2FsdGVkX1+sbxYhz6J85FIgYOJI80uTYCrh5BnYer4=",
                  "prenom": "U2FsdGVkX1+SJRXFR72iFEpg2CYvVOY8XwODbx4DTZY=",
                  "adresse": "U2FsdGVkX19UkwxFmpPv4EG8sZuZlMt0IaBjaZec2eKbQ66OMx7pC9F/ebQfZBdg",
                  "telephone": "U2FsdGVkX1+/ZxBkkur0NV69kp0M53CjiLWt493XOyE=",
                  "ville": "U2FsdGVkX1+9/+5ojL4rRKx2dVwiJZLCoeXFuQZMKF0=",
                  "codePostal": "U2FsdGVkX1+zm5ReV0iYmp3JKKCQcx1oQ5aq68ydbmM=",
                  "email": "tom@gmail.com",
                  "password": "$2b$10$gvRD1O03h5uX/u2qG8mJf.va.J/ZwTtITj6AsBgLU2ctaEoIMdGju",
                  "_id": "654d0526cfee7152a302daa9",
                  "__v": 0
                }
              ] 
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/clients/delete": {
      "delete": {
        "tags": [
          "Clients"
        ],
        "summary": "Supprime un client en fonction de son token",
        "security": [
          {
            "Bearer": [] 
          }
        ],
        "responses": {
          "200": {
            "description": "Opération réussie. Retourne le client supprimé."
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/clients/update": {
      "post": {
        "tags": [
          "Clients"
        ],
        "summary": "Modifie un client",
        "parameters": [
          {
            "in": "formData",
            "name": "nom",
            "type": "string",
            "required": false,
            "description": "Votre nom"
          },
          {
            "in": "formData",
            "name": "prenom",
            "type": "string",
            "required": false,
            "description": "Votre prenom"
          },
          {
            "in": "formData",
            "name": "adresse",
            "type": "string",
            "required": false,
            "description": "Votre adresse"
          },
          {
            "in": "formData",
            "name": "telephone",
            "type": "string",
            "required": false,
            "description": "Votre telephone"
          },
          {
            "in": "formData",
            "name": "ville",
            "type": "string",
            "required": false,
            "description": "Votre ville"
          },
          {
            "in": "formData",
            "name": "codePostal",
            "type": "string",
            "required": false,
            "description": "Votre code postal"
          },
          {
            "in": "formData",
            "name": "email",
            "type": "string",
            "required": false,
            "description": "Votre email"
          },
          {
            "in": "formData",
            "name": "password",
            "type": "string",
            "required": false,
            "description": "Votre mot de passe"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/clients/connect": {
      "post": {
        "tags": [
          "Clients"
        ],
        "description": "Connectez-vous en utilisant un email et un mot de passe.",
        "parameters": [
          {
            "in": "formData",
            "name": "email",
            "type": "string",
            "required": true,
            "description": "Votre email"
          },
          {
            "in": "formData",
            "name": "password",
            "type": "string",
            "required": true,
            "description": "Votre mot de passe"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/clients/updatePassword": {
      "post": {
        "tags": [
          "Clients"
        ],
        "description": "",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "example": "any"
                },
                "password": {
                  "example": "any"
                },
                "newPassword": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },











    
    "/get/{id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/update/{id}": {
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "nom": {
                  "example": "any"
                },
                "promotion": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/delete/{id}": {
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/getDatesReservations": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },

  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },

"components": {

  "responses":{
    "200":{
      "description": "OK. La requête a abouti."
    },
    "401":{
      "description": "Échec de l'authentification. Les informations d'identification sont incorrectes."
    },
    "404":{
      "description": "Requête invalide. Les paramètres sont manquant/incorrects."
    },
    "500":{
      "description": "Erreur serveur. Une erreur s'est produite lors de la récupération des clients."
    }
      
  }
},

"security": {
  "Bearer": []
}


}